import { Suspense } from 'react';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ProgressBar } from 'src/components/Progressbar';
import 'nprogress/nprogress.css';
import './globals.css'
import Nav from 'src/components/Nav';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <>
          {Nav()}
          {children}
          <Suspense fallback={null}>
            <ProgressBar />
          </Suspense>
        </>
      </body>
    </html>
  );
}
